import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { LogOut, Pencil, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { deleteProduct, listAdminProducts, saveProduct } from "@/lib/products.functions";
import { money, splitList, type Product } from "@/lib/products";

export const Route = createFileRoute("/admin")({ ssr: false, component: AdminPage });
const empty = { name: "", slug: "", description: "", category: "T-Shirts", price: "", images: "", colors: "", sizes: "S, M, L, XL", in_stock: true, featured: false, published: false };
function AdminPage() { const navigate = useNavigate(); const client = useQueryClient(); const [ready, setReady] = useState(false); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | undefined>(); const [message, setMessage] = useState(""); useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (!data.user) navigate({ to: "/auth" }); else setReady(true); }); }, [navigate]); const query = useQuery({ queryKey: ["admin-products"], queryFn: () => listAdminProducts(), enabled: ready, retry: false });
  const save = useMutation({ mutationFn: () => saveProduct({ data: { id: editing, name: form.name, slug: form.slug, description: form.description, category: form.category, price: form.price ? Number(form.price) : null, images: splitList(form.images), colors: splitList(form.colors), sizes: splitList(form.sizes), in_stock: form.in_stock, featured: form.featured, published: form.published } }), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin-products"] }); setForm(empty); setEditing(undefined); setMessage("Product saved."); }, onError: (error) => setMessage(error.message) });
  const edit = (p: Product) => { setEditing(p.id); setForm({ name: p.name, slug: p.slug, description: p.description, category: p.category, price: p.price?.toString() ?? "", images: p.images.join(", "), colors: p.colors.join(", "), sizes: p.sizes.join(", "), in_stock: p.in_stock, featured: p.featured, published: p.published }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  if (!ready) return <div className="p-12">Checking access…</div>;
  if (query.error) return <div className="mx-auto max-w-xl px-4 py-20"><h1 className="font-display text-4xl uppercase">Admin access required</h1><p className="mt-4 text-muted-foreground">Sign in with simbinikhalaza@gmail.com to manage this store.</p><Button className="mt-6" onClick={async () => { await supabase.auth.signOut(); navigate({ to: "/auth" }); }}>Use another account</Button></div>;
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="flex items-start justify-between"><div><p className="text-sm font-black uppercase tracking-[.3em] text-primary">Den Mond backend</p><h1 className="font-display mt-2 text-4xl font-black uppercase sm:text-6xl">Manage products</h1></div><Button variant="outline" size="icon" onClick={async () => { await client.cancelQueries(); client.clear(); await supabase.auth.signOut(); navigate({ to: "/auth", replace: true }); }}><LogOut/></Button></div>
    <section className="mt-10 border border-border bg-card p-5 sm:p-8"><div className="flex justify-between"><h2 className="font-display text-2xl font-black uppercase">{editing ? "Edit product" : "New product"}</h2>{editing && <Button variant="ghost" size="icon" onClick={() => { setEditing(undefined); setForm(empty); }}><X/></Button>}</div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Product name"><Input value={form.name} maxLength={120} onChange={(e) => setForm({ ...form, name: e.target.value, slug: editing ? form.slug : e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") })}/></Field><Field label="URL slug"><Input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })}/></Field><Field label="Category"><Input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}/></Field><Field label="Price (ZAR)"><Input type="number" min="0" step="0.01" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })}/></Field><Field label="Description" wide><Textarea className="min-h-28" value={form.description} maxLength={2000} onChange={(e) => setForm({ ...form, description: e.target.value })}/></Field><Field label="Image URLs — separate with commas" wide><Textarea value={form.images} onChange={(e) => setForm({ ...form, images: e.target.value })}/></Field><Field label="Colours — separate with commas"><Input value={form.colors} onChange={(e) => setForm({ ...form, colors: e.target.value })}/></Field><Field label="Sizes — separate with commas"><Input value={form.sizes} onChange={(e) => setForm({ ...form, sizes: e.target.value })}/></Field></div><div className="mt-5 flex flex-wrap gap-5">{(["in_stock","featured","published"] as const).map((key) => <label key={key} className="flex items-center gap-2 text-sm font-bold uppercase"><input type="checkbox" checked={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.checked })}/>{key.replace("_", " ")}</label>)}</div><Button className="mt-7 h-12 rounded-none px-8" disabled={save.isPending || !form.name || !form.slug} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : <><Plus/> Save product</>}</Button>{message && <p className="mt-3 text-sm text-muted-foreground">{message}</p>}<p className="mt-4 text-xs text-muted-foreground">Image uploads are currently workspace-restricted; paste hosted image URLs here. Existing supplied product images are already connected.</p></section>
    <section className="mt-12"><h2 className="font-display text-3xl font-black uppercase">Catalog ({query.data?.length ?? 0})</h2><div className="mt-6 divide-y divide-border border-y border-border">{query.data?.map((p) => <article key={p.id} className="grid grid-cols-[72px_1fr] gap-4 py-5 sm:grid-cols-[96px_1fr_auto]"><div className="bg-muted">{p.images[0] && <img src={p.images[0]} alt="" className="aspect-square h-full w-full object-cover"/>}</div><div><div className="flex items-center gap-2"><h3 className="font-display text-lg font-black uppercase">{p.name}</h3><span className={`px-2 py-1 text-[10px] font-bold uppercase ${p.published ? "bg-primary text-primary-foreground" : "bg-muted"}`}>{p.published ? "Live" : "Draft"}</span></div><p className="text-sm text-muted-foreground">{p.category} · {money(p.price)}</p></div><div className="col-span-2 flex gap-2 sm:col-span-1"><Button variant="outline" size="sm" onClick={() => edit(p)}><Pencil/> Edit</Button><Button variant="destructive" size="sm" onClick={async () => { if (!window.confirm(`Delete ${p.name}?`)) return; await deleteProduct({ data: { id: p.id } }); client.invalidateQueries({ queryKey: ["admin-products"] }); }}><Trash2/> Delete</Button></div></article>)}</div></section>
  </div>; }
function Field({ label, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? "sm:col-span-2" : ""}><span className="mb-2 block text-xs font-black uppercase tracking-wider">{label}</span>{children}</label>; }